### ISSUE TITLE
SDRConnect Dockerfile

### ISSUE THREAD

**Issue by XMaarten** [dgadams/sdrpp-server#1]
Could you please publish your Dockerfile for https://hub.docker.com/r/dgadams/sdr-connect as well? 

Your container is build for AMD64, but I would like to build a container for ARM64 (for a Raspberry Pi 4) myself. I am having some trouble with accepting the license within Docker when I try to create something myself.

Sorry to abuse sdrpp-server for this request, but I don't see another way to get in touch with you.

**Comment by dgadams** [comment]
Done.  See https://github.com/dgadams/sdr-connect

The trick is this line:
./sdrc.run --tar xvf .

This extracts the .run file bypassing the license stuff.
Not my idea.  Got it when building sdrpp-server.

Doug Adams
